name: Static code analysis / linting

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./firmware

    steps:
      - uses: actions/checkout@v3
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      #- name: clang-format Check
        #uses: jidicula/clang-format-action@v4.11.0
      